name: facebook-pages-api-web
static_sites:
- name: privacy-policy-app
  source_dir: /
  github:
    repo: kathawut/fb-page-service-web
    branch: main
  build_command: npm run build && cp public/comments-tester.html dist/
  output_dir: dist
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
  - path: /comments-tester.html
  catchall_document: index.html
  envs:
  - key: NODE_ENV
    value: production
