name: facebook-pages-api-web
services:
- name: web
  source_dir: /
  github:
    repo: kathawut/fb-page-service-web
    branch: main
  build_command: npm run build && cp public/comments-tester.html dist/
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
